import localfont from "next/font/local";
import "./globals.css";
import Navbar from "./components/header/Navbar";
import Footer from "./components/footer/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SideNavbar from "./components/header/SideNavbar";


const nunito = localfont({
  src: [
    {
      path: "../../public/fonts/Nunito-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/Nunito-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/Nunito-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/Nunito-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Nunito-Light.ttf",
      weight: "300",
    }
  ],
  variable:"--font-nunito"
});
const libreCaslon = localfont({
  src: [
    {
      path: "../../public/fonts/LibreCaslonText-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/LibreCaslonText-Regular.ttf",
      weight: "400",
    },
  ],
  variable:"--font-libreCaslon"
});
const Montserrat = localfont({
  src: [
    {
      path: "../../public/fonts/Montserrat-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/Montserrat-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/Montserrat-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/Montserrat-Regular.ttf",
      weight: "400",
    },
  ],
  variable:"--font-Montserrat"
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${libreCaslon.variable} ${Montserrat.variable} `}>
        <Navbar />
        {/* <SideNavbar/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
